

trigger: none

pool: my-agent

steps:
- script: echo Hello, my-agent!
  displayName: 'print my agent name'

- task: TerraformInstaller@1
  displayName: Terraform install
  inputs:
    terraformVersion: 'latest'
