trigger: none

pool: my-agent

jobs:
- job: test
  displayName: terraform init & plan
  steps:
  - task: TerraformTask@5
    displayName: Terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\root_module\dev-env'
      backendServiceArm: 'my-service'
      backendAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
      backendAzureRmResourceGroupName: 'backend-rg'
      backendAzureRmStorageAccountName: 'backendsta'
      backendAzureRmContainerName: 'backendcontainer'
      backendAzureRmKey: 'dev1.tfstate'

  - task: TerraformTask@5
    displayName: Terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)\root_module\dev-env'
      environmentServiceNameAzureRM: 'my-service'
      environmentAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'

- job: manualValidation
  displayName: manual validation
  pool: server
  dependsOn: test
  steps:
  - task: ManualValidation@1
    inputs:
      instructions: "Please review the Terraform plan before apply"
      notifyUsers: |
        satya@tarundevops1outlook.onmicrosoft.com
      approvers: |
        satya@tarundevops1outlook.onmicrosoft.com
      onTimeout: 'reject'
      timeout: '1d'

- job: apply
  displayName: Terraform Apply
  dependsOn: manualValidation
  steps:
  - task: TerraformTask@5
    displayName: Terraform apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)\root_module\dev-env'
      environmentServiceNameAzureRM: 'my-service'
      environmentAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
