trigger: none

pool: my-agent

steps:
- script: echo Hello, my-agent!
  displayName: 'print my agent name'

- task: TerraformInstaller@1
  displayName: Terraform install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'C:\Users\hp\Downloads\my-agent\vsts-agent-win-x64-4.260.0 (1)\_work\2\s\root_module\dev-env'
    backendServiceArm: 'my-service'
    backendAzureRmOverrideSubscriptionID: '81cc1915-8d88-419e-8fa3-0178811761bd'
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmStorageAccountName: 'backendsta'
    backendAzureRmContainerName: 'backendcontainer'
    backendAzureRmKey: 'dev.tfstate'
